### ISSUE TITLE
err, errors not nil

### ISSUE THREAD

**Issue by markschmid** [FusionAuth/go-client#12]
FusionAuthClient API methods return a ```response```, ```errors```and ```err```.
The Example syntax advises to check ```errors``` and ```err``` for nil to determine if there were errors.

I was playing around with the newest go-client against a FusionAuth version 1.11.0 installation and discovered, that e.g.

after a successful ```CreateTenant()``` call (HTTP 200), ```errors``` is not nil but ```&{map[] []}```
after a successful ```DeleteTenant()``` call (HTTP 200), ```err``` is not nil but ```EOF``` and errors is also ```&{map[] []}```

Maybe I'm just a little confused, but shouldn't they be nil?

**Comment by matthew-altman** [comment]
@markschmid thanks for being invested enough to share your findings with us as we're working through this new client. I've updated the client-builder and regenerated the go-client with the suggested behavior. Thanks!

**Comment by markschmid** [comment]
Great, thanks @matthew-altman ! For successful calls I'm getting now getting ```nil``` for ```errors``` and ```err```.

E.g. for a call that results in 404 ```err``` and ```errors``` are still non-nil (```EOF``` and ```&{map[] []}``` respectively). I suppose that's intended.

For ```errors```, I can additionally check for empty struct besides ```nil```, no problem. For ```err```, can I assume ```EOF``` bears the same meaning ```nil``` in those cases?

**Comment by matthew-altman** [comment]
@markschmid since there are lots of different reasons for failures there would probably be a lot of conditional checks that I could do to determine if/when to populate the err and errors. In your most recent example the err is probably returning an EOF since we're attempting to load the errors object with the response for a non successful call. However, a 404 wouldn't return validation errors. This is perhaps something we can address in a future iteration.
