### ISSUE TITLE
Make clientID and clientSecret optional in ExchangeOAuthCodeForAccessToken()

### ISSUE THREAD

**Issue by markschmid** [FusionAuth/go-client#33]
I think the method ExchangeOAuthCodeForAccessToken() is not taking care of the optional params ```clientID``` and ```clientSecret```. I'm using the values "" (my take of optional), yet the response of FA is:
```The request is missing a required parameter: client_id missing_client_id```

**Comment by markschmid** [comment]
Remark: In Line https://github.com/FusionAuth/go-client/blob/ca7d656cda77bc8cff485e1bdf110c82e118e8b7/pkg/fusionauth/Client.go#L1272 the client is used anonymously (without the Authorization header). I think it should support using the API Key as well.

**Comment by robotdan** [comment]
The `/oauth2/token` endpoint does not accept an API key, this is why it is using the `StartAnonymous`. 

The way the method is constructed, the `client_id` and `client_secret` are required. The `Authorization` header that is referred to in the comment is the HTTP Basic Authorization header which would use the `client_id` and `client_secret` in an authorization header instead of the request body. 

We could update the comment since this usage does not use the HTTP Basic Authorization for client authentication. 

Is there a reason you can't pass the `client_id` and `client_secret` as arguments to this method?

**Comment by markschmid** [comment]
Thanks for the clarification. Reading the „optional“ lead to false conclusions on my side.

**Comment by robotdan** [comment]
You're welcome, yes, the wording was confusing. I have updated that in commit https://github.com/FusionAuth/fusionauth-client-builder/commit/32ae5b8268d7d7001468cc51a50e2b20deda1520 and https://github.com/FusionAuth/go-client/commit/dbc3c6c38f1e8f40d455394e6a6343e77a8ebb75.

**Comment by robotdan** [comment]
Assuming we can close out this issue?

**Comment by markschmid** [comment]
Absolutely, thanks again!
